export enum Permission {
  // Tenant
  MANAGE_TENANT = 'MANAGE_TENANT',

  // User Management
  MANAGE_USERS = 'MANAGE_USERS',
  READ_USERS = 'READ_USERS',

  // Content (CMS)
  CREATE_CONTENT = 'CREATE_CONTENT',
  READ_CONTENT = 'READ_CONTENT',
  UPDATE_CONTENT = 'UPDATE_CONTENT',
  DELETE_CONTENT = 'DELETE_CONTENT',
  PUBLISH_CONTENT = 'PUBLISH_CONTENT',

  // Media
  MANAGE_MEDIA = 'MANAGE_MEDIA',
  READ_MEDIA = 'READ_MEDIA',
}
